---
title: 'Master 2 thesis : Biodiversity and resilience of tropical forest ecosystem'
author: Sylvain Schmitt
date: '2017-08-02'
slug: master-thesis
categories:
  - modelling
  - TROLL
  - sylviculture
tags:
  - bayesian modelling
  - master 2
  - TROLL forest simulator
projects: TROLL
header:
  caption: ''
  image: ''
csl: /home/sylvain/Documents/Bibliography/csl/mee.csl
bibliography: /home/sylvain/Documents/Bibliography/library.bib
summary: "I defended my master 2 thesis entitled: *The role of biodiversity in the resilience of tropical forest ecosystems after disturbance*."
---

# Abstract

Forest disturbances are the third worldwide source of greenhous gas. Tropical deforestation and degradation emit 8.26 billion of tons of carbon dioxyde per year [@Pearson2017]. Deforestation has retained much attention, but degradation from forest represents 20% of emissions in brazilian Amazon [@Asner2005]. Sustainable forest management has been promoted as an answer to deforestation and degradation, besides logging sustainability has been questionned [@Zimmerman2012]. On the other hand, tropical forest host over half of the Earth's biodiversity [@Scheffers2012]. Consequently, we decided to study the role of biodiversity in forest ecosystem answer to disturbance, linking diversity to ecosystem functionning [@Loreau2010]. We used the hypothesis that when a disturbance event happen, due to a higher productivity, a more diverse forest will be more resilient, based on the positive relationship between biodiversity and productivity. We linked that hypothesis to the complementarity and selection effects [@Loreau2001]. Complementarity is the addition of ressource partitionning and facilitation, whereas selection effect is the result of competitive selection. We thus focused on mechanisms involved in the relationship between biodiversity and forest ecosystem resilience with a simulation approach to assess long term processes. We used TROLL model [@Li] to simulate 60 matures forests with growing taxonomic and functional  diversities. We disturbed all forests and measured the resilience of their  ecosystem functions. Additionnally, we measured biodiversity net effect resilience partitioned into complementarity and selection effects. We found that diversity improved tropical forest resilience, particularly through functional diversity and eveness. Moreover, we showed that complementarity between species insured forest recovery in the beginning of the succession before being replaced by selection effect. Our results suggest the possibility for a sustainable management of tropical forest due to an increased resilience with an higher diversity. But this conclusion has meaning only if selective logging meet sustainability [@Zimmerman2012]. On the contrary, unsustainable tropical forest management will lead to negative feedbacks slowly diminishing diversity and thus forest resilience, resulting ultimately in forest degradation.

# References
